canonical: http://hl7.org/fhir/us/bser
title: "Bidirectional Services eReferral (BSeR)"
releaseLabel: STU2
fhirVersion: 4.0.1
FSHOnly: false
applyExtensionMetadataToRoot: false
id: hl7.fhir.us.bser
name: BSeRBidirectionalServicesEReferral
status: active
version: 2.0.0-ballot

dependencies:
  us.cdc.phinvads:
    version: 0.12.0
    uri: http://fhir.org/packages/us.cdc.phinvads/ImplementationGuide/us.cdc.phinvads
    id: uscdcphinvads
  us.nlm.vsac:
    version: 0.11.0
    uri: http://fhir.org/packages/us.nlm.vsac/ImplementationGuide/us.nlm.vsac
    id: usnlmvsac
  hl7.fhir.us.core:
    version: 5.0.1
    uri: http://hl7.org/fhir/us/core/ImplementationGuide/hl7.fhir.us.core
    id: hl7fhiruscore
  hl7.fhir.us.odh:
    version: 1.3.0
    uri: http://hl7.org/fhir/us/odh/ImplementationGuide/hl7.fhir.us.odh
    id: hl7fhirusodh

pages:
  index.md:
    title: Home Page
  Introduction.md:
    title: Introduction
  bser_project_team.md:
    title: BSeR Project Team
  Acknowledgements.md:
    title: Acknowledgements
  scope_and_context.md:
    title: Scope and Context
  resource_profiles.md:
    title: Resource Profiles
  referral_participant_resources.md:
    title: Referral Participant Resources
  workflow_management_resources.md:
    title: Workflow Management Resources
  referral_service_request_resources.md:
    title: Referral Service Request Resources
  referral_service_request_feedback_resources.md:
    title: Referral Service Request Feedback Resources
  service_request_and_referral_feedback_supporting_information.md:
    title: Service Request and Referral Feedback Supporting Information
  bi-directional_service_ereferral_transactions.md:
    title: Bi-directional Service eReferral Transactions
  transport_options.md:
    title: Transport Options
  adaptation_for_additional_referral_use_cases.md:
    title: Adaptation for Additional Referral Use Cases
  Downloads.md:
    title: Downloads
  change_log.md:
    title: Change Log

menu:
  Home: index.html
  Table of Contents: toc.html
  Background:
    Introduction: Introduction.html
    BSeR Project Team: bser_project_team.html
    Acknowledgements: Acknowledgements.html
    Scope and Context: scope_and_context.html
    Change Log: change_log.html
  Resource Profile Information:
    Resource Profiles: resource_profiles.html
    Referral Participant Resources: referral_participant_resources.html
    Workflow Management Resources: workflow_management_resources.html
    Referral Service Request Resources: referral_service_request_resources.html
    Referral Service Request Feedback Resources: referral_service_request_feedback_resources.html
    Service Request and Referral Feedback Supporting Information: service_request_and_referral_feedback_supporting_information.html
    Bi-directional Service e-Referral Transactions: bi-directional_service_ereferral_transactions.html
    Transport Options: transport_options.html
    Adaptation for Additional Referral Use Cases: adaptation_for_additional_referral_use_cases.html
  Downloads: Downloads.html
  Artifact Index: artifacts.html

groups:
  core-referral-architecture-profiles:
    name: Core Referral Architecture Profiles
    # description: Core Referral Architecture Profiles
    resources:
    - StructureDefinition/referral-task
    - StructureDefinition/referral-servicerequest
  workflow-management-profiles:
    name: Workflow Management Profiles
    # description: Workflow Management Profiles
    resources:
    - StructureDefinition/BSeR-ReferralMessageHeader
    - StructureDefinition/BSeR-ReferralTask
  referral-service-request-profiles:
    name: Referral Service Request Profiles
    # description: Referral Service Request Profiles
    resources:
    - StructureDefinition/BSeR-ReferralServiceRequest
    - StructureDefinition/BSeR-ReferralRequestComposition
    - StructureDefinition/BSeR-ReferralRequestDocumentBundle
    - StructureDefinition/BSeR-ReferralMessageBundle
  referral-service-request-feedback-profiles:
    name: Referral Service Request Feedback Profiles
    # description: Referral Service Request Feedback Profiles
    resources:
    - StructureDefinition/BSeR-ReferralActivityStatus
    - StructureDefinition/BSeR-ReferralFeedbackComposition
    - StructureDefinition/BSeR-ReferralFeedbackDocumentBundle
  supporting-information-profiles:
    name: Supporting Information Profiles (Request and Feedback)
    # description: Supporting Information Profiles (Request and Feedback)
    resources:
    - StructureDefinition/bser-bundle-batch-query-referral-supporting-info
    - StructureDefinition/bser-referral-observation
    - StructureDefinition/BSeR-TelcomCommunicationPreferences
    - StructureDefinition/BSeR-TobaccoUseCessationFeedbackMedication
  other-profiles:
    name: Other Profiles
    # description: Other Profiles
    resources:
    - StructureDefinition/BSeR-Coverage
    - StructureDefinition/BSeR-PatientConsent
  batch-query-bundle-referral-request-examples:
    name: Batch Query Bundle Referral Request Examples
    description: Examples of referral request batch query Bundles for each use case described in the BSeR IG. Each Bundle is a batch of queries for definition and/or retrieval of supporting information for a use case specific referral request.
    resources:
    - Bundle/bundle-batch-query-arthritis-request
    - Bundle/bundle-batch-query-diabetes-prevention-request
    - Bundle/bundle-batch-query-early-childhood-nutrition-request
    - Bundle/bundle-batch-query-hypertension-request
    - Bundle/bundle-batch-query-obesity-request
    - Bundle/bundle-batch-query-tobacco-use-cessation-request
  batch-query-bundle-referral-feedback-examples:
    name: Batch Query Bundle Referral Feedback Examples
    description: Examples of referral feedback batch query Bundles for each use case described in the BSeR IG. Each Bundle is a batch of queries for definition and/or retrieval of supporting information for use case specific referral feedback.
    resources:
    - Bundle/bundle-batch-query-arthritis-feedback
    - Bundle/bundle-batch-query-diabetes-prevention-feedback
    - Bundle/bundle-batch-query-early-childhood-nutrition-feedback
    - Bundle/bundle-batch-query-hypertension-feedback
    - Bundle/bundle-batch-query-obesity-feedback
    - Bundle/bundle-batch-query-tobacco-use-cessation-feedback
  # batch-response-bundle-examples:
  #   name: Batch Response Supporting Information Bundle Examples for Referral Requests
  #   description: Examples of batch query Bundles for each use case. Each Bundle is a batch of queries for definition and/or retrieval of supporting information for a use case specific referral request or referral feedback.
  #   resources:
  #   - Bundle/bundle-batch-response-arthritis-request-supp-info
  #   - Bundle/bundle-batch-response-diabetes-prevention-request-supp-info
  #   - Bundle/bundle-batch-response-early-childhood-request-supp-info
  #   - Bundle/bundle-batch-response-hypertension-request-supp-info
  #   - Bundle/bundle-batch-response-obesity-request-supp-info
  #   - Bundle/bundle-batch-response-tobacco-use-request-supp-info
  # name: Batch Response Supporting Information Bundle Examples for Referral Feedback
  #   description: Examples of batch query Bundles for each use case. Each Bundle is a batch of queries for definition and/or retrieval of supporting information for a use case specific referral request or referral feedback.
  #   resources:
  #   - Bundle/bundle-batch-query-arthritis-feedback
  #   - Bundle/bundle-batch-query-diabetes-prevention-feedback
  #   - Bundle/bundle-batch-query-early-childhood-nutrition-feedback
  #   - Bundle/bundle-batch-query-hypertension-feedback
  #   - Bundle/bundle-batch-query-obesity-feedback
  #   - Bundle/bundle-batch-query-tobacco-use-cessation-feedback
  core-referral-architecture-examples:
    name: Core Referral Architecture Examples
    # description: Core Referral Architecture Examples
    resources:
    - ServiceRequest/servicerequest-referral-servicerequest
    - Task/task-referral-task
  workflow-management-examples:
    name: Workflow Management Examples
    # description: Workflow Management Examples
    resources:
    - MessageHeader/messageheader-bser-referral-messageheader
    - Task/task-bser-referral-task
  referral-service-request-examples:
    name: Referral Service Request Examples
    # description: Referral Service Request Examples
    resources:
    - Bundle/bundle-bser-referral-message-bundle-eve-everywoman
    - Bundle/bundle-bser-referral-request-document-bundle-eve-everywoman
    - Bundle/bundle-bser-referral-request-document-bundle-baby-everybaby
    - ServiceRequest/servicerequest-bser-referral-servicerequest-arthritis
    - ServiceRequest/servicerequest-bser-referral-servicerequest-early-childhood
  referral-serivce-request-examples-composition:
    name: "Referral Service Request Examples: Composition"
    # description: "Referral Service Request Examples: Composition"
    resources:
    - Composition/composition-bser-referral-request-arthritis-everywoman
    - Composition/composition-bser-referral-request-diabetes-everywoman
    - Composition/composition-bser-referral-request-hypertension-everywoman
    - Composition/composition-bser-referral-request-obesity-everywoman
    - Composition/composition-bser-referral-request-tobacco-everywoman
    - Composition/composition-bser-referral-request-nutrition-everybaby
  referral-service-request-feedback-examples:
    name: Referral Service Request Feedback Examples
    # description: Referral Service Request Feedback Examples
    resources:
    - Bundle/bundle-bser-referral-feedback-document-bundle-eve-everywoman
    - Observation/observation-bser-referralactivitystatus-eve-everywoman
  referral-service-request-feedback-examples-composition:
    name: "Referral Service Request Feedback Examples: Composition"
    # description: "Referral Service Request Feedback Examples: Composition"
    resources:
    - Composition/composition-bser-referral-feedback-arthritis-everywoman
    - Composition/composition-bser-referral-feedback-nutrition-everybaby
    # - Composition/composition-bser-referral-feedback-diabetes-everywoman
    # - Composition/composition-bser-referral-feedback-hypertension-everywoman
    # - Composition/composition-bser-referral-feedback-obesity-everywoman
    # - Composition/composition-bser-referral-feedback-tobacco-everywoman
  supporting-information-examples:
    name: Supporting Information Examples
    # description: Supporting Information Examples
    resources:
    - AllergyIntolerance/allergyintolerance-us-core-allergyint-eve-everywoman
    - Condition/condition-us-core-cphc-eve-everywoman-hypertension
    - Observation/observation-us-core-observation-lab-ha1c-eve-everywoman
    - Procedure/procedure-us-core-procedure-nicotine-replacement-eve-everywoman
    - Observation/observation-bser-referral-observation-lactation-baby-everybaby
    - Observation/observation-bser-nutritionfeedbackobs-2-baby-everybaby
    - Observation/observation-bser-nutritionobs-baby-everybaby
    - Observation/observation-bser-telcomcomm-eve-everywoman
    - Observation/observation-us-core-blood-pressure-eve-everywoman
    - Observation/observation-us-core-blood-pressure-baby-everybaby
    - Observation/observation-us-core-blood-pressure-mom-everymom
    - Observation/observation-us-core-bmi-eve-everywoman
    - Observation/observation-us-core-bmi-mom-everymom
    - Observation/observation-us-core-body-height-baby-everybaby
    - Observation/observation-us-core-body-height-eve-everywoman
    - Observation/observation-us-core-body-height-mom-everymom
    - Observation/observation-us-core-body-weight-eve-everywoman
    - Observation/observation-us-core-body-weight-baby-everybaby
    - Observation/observation-us-core-body-weight-mom-everymom
    - Observation/observation-odh-employment-status-eve-everywoman
    - Observation/observation-odh-employment-status-mom-everymom
    - Observation/observation-us-core-smokingstatus-eve-everywoman
  supporting-information-feedback-examples:
    name: Supporting Information Feedback Examples
    # description: Supporting Information Feedback Examples
    resources:
    - Medication/medication-bser-tobacco-use-cessation-feedback-eve-everywoman
    - MedicationRequest/medicationrequest-us-core-medicationrequest-eve-everywoman
    - Observation/observation-bser-tobaccousecessationfeedbackobs-1-eve-everywoman
    - Observation/observation-bser-tobaccousecessationfeedbackobs-2-eve-everywoman
    - Observation/observation-participationfeedbackobservation-1-eve-everywoman
    - Observation/observation-participationfeedbackobservation-2-eve-everywoman
    - Observation/observation-bser-referral-observation-pain-mgmt-eve-everywoman
    - Observation/observation-bser-referral-observation-endurance-eve-everywoman
  referral-participant-examples:
    name: Referral Participant Examples
    # description: Referral Participant Examples
    resources:
    - Location/location-us-core-location-st-luke
    - Organization/organization-us-core-organization-acme-lab
    - Organization/organization-us-core-organization-saint-luke
    - Patient/patient-us-core-patient-baby-everybaby
    - Patient/patient-us-core-patient-eve-everywoman
    - Patient/patient-us-core-patient-mom-everymom
    - Practitioner/practitioner-us-core-practitioner-hailey-eight
    - Practitioner/practitioner-us-core-practitioner-henry-seven
    - PractitionerRole/practitionerrole-us-core-practitionerrole-referral-initiator
    - PractitionerRole/practitionerrole-us-core-practitionerrole-referral-recipient
    - RelatedPerson/relatedperson-us-core-relatedperson-mom-everymom
    # - RelatedPerson/relatedperson-us-core-relatedperson-self-eve-everywoman
    - RelatedPerson/relatedperson-us-core-relatedperson-mother-eve-everywoman
  other-examples:
    name: Other Examples
    resources:
    - Consent/consent-bser-patientconsent-eve-everywoman
    - Consent/consent-bser-patientconsent-baby-everybaby
    - Coverage/coverage-bser-coverage-eve-everywoman
    - Coverage/coverage-bser-coverage-baby-everybaby
    - Observation/observation-us-core-social-history-education-eve-everywoman
    - Observation/observation-us-core-social-history-education-mom-everymom
  code-systems:
    name: Code Systems
    resources:
    - CodeSystem/TaskBusinessStatusCS
    - CodeSystem/bser
  value-sets:
    name: Value Sets
    resources:
    - ValueSet/BSeR-TelcomCommunicationPreferencesVS
    - ValueSet/TaskBusinessStatusVS
  capability-statement:
    name: Capability Statement
    resources:
    - CapabilityStatement/capabilitystatement-bser
  other:
    name: Other
    resources:
    - parameters-snomed-us

copyrightYear: 2022+
publisher:
  name: HL7 Public Health Working Group
  url: http://www.hl7.org/Special/committees/pher
  email: pher@lists.HL7.org
parameters:
  show-inherited-invariants: false
  path-expansion-params: 'Parameters-parameters-snomed-us.json'  #path is relative to [base]/fsh-generated/resources
  auto-oid-root: 2.16.840.1.113883.4.642.40.33

jurisdiction: urn:iso:std:iso:3166#US
license: CC0-1.0